name: GitHub Course-Review-Api

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch on GitHub
        uses: actions/checkout@v3
        
      - name: Move old app.py and database.py to a save place
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo mkdir --parents ${{ secrets.TARGET_DIRECTORY }}/oldVersions/$(date +%Y%m%d_%H%M%S) && sudo mv ${{ secrets.TARGET_DIRECTORY }}/app.py $_ && sudo mv ${{ secrets.TARGET_DIRECTORY }}/database.py $_
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}

      - name: Deploy app.py to server
        uses: garygrossgarten/github-action-scp@release
        with:
          atomicPut: true    
          local: app.py
          remote: ${{ secrets.TARGET_DIRECTORY }}/app.py
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          
      - name: Deploy database.py to server
        uses: garygrossgarten/github-action-scp@release
        with:
          atomicPut: true    
          local: database.py
          remote: ${{ secrets.TARGET_DIRECTORY }}/database.py
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          
      - name: Restart the API
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl restart CRapi
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
