name: Course-Review-Api Testing

env:
  RDD: ${{ secrets.RDD }}
  USERNAME: ${{ secrets.API_USERNAME }}
  PASSWORD: ${{ secrets.API_PASSWORD }}
  TESTING_URL: ${{ secrets.TESTING_URL }}

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the main branch on GitHub
        uses: actions/checkout@v3
        
      - name: Deploy app.py to server
        uses: garygrossgarten/github-action-scp@release
        with:
          atomicPut: true    
          local: app.py
          remote: ${{ secrets.TESTING_TARGET_DIRECTORY }}/app_test.py
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          
      - name: Deploy database.py to server
        uses: garygrossgarten/github-action-scp@release
        with:
          atomicPut: true    
          local: database.py
          remote: ${{ secrets.TESTING_TARGET_DIRECTORY }}/database_test.py
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
          
      - name: Start the testing API
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl start CRapi_test
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: execute py script
        run: python testing/apiTest.py  

      - name: Stopping the testing API
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: sudo systemctl stop CRapi_test
          host: ${{ secrets.VSOS_IP_ADDRESS }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.SSH_KEY }}
